### ISSUE TITLE
Upgrade to Camden

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-deployer#114]
As a developer, I'd like to upgrade to Camden, so all the upstream release dependencies are synchronized.

**Comment by ericbottard** [comment]
Reopening, as full upgrade should also have upgraded the spring-cloud-build dependency, which brings in its share of required changes.

Will issue a second PR, that also bumps master to 1.1.0.BUILD-SNAPSHOT
