### ISSUE TITLE
Add configuration properties metadata to jar

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-deployer#121]
There's no metadata so IDE autocompletion is not working for these libraries. It's easy to do (just an optional dependency on the configuration processor).

**Comment by ilayaperumalg** [comment]
Given there aren't specific `@ConfigurationProperties` in `spring-cloud-deployer-spi` and other related sub projects in this repo, I think it may not be needed to add the `configuration-processor` dependency for this project. Instead, I verified few other `spring-cloud-deployer` implementations and `spring-cloud-dataflow` server core/shell core projects where this would be helpful. Addressed the same in the respective projects{

https://github.com/spring-cloud/spring-cloud-dataflow/pull/1234
https://github.com/spring-cloud/spring-cloud-deployer-local/pull/34
https://github.com/spring-cloud/spring-cloud-deployer-kubernetes/pull/117
https://github.com/spring-cloud/spring-cloud-deployer-mesos/pull/56

An interesting thing to note here is that, the `MavenProperties` and other deployer properties mentioned in `AppDeployer` contract are not deemed to be `ConfigurationProperties` until they get used in the respective implementations (deployer implementation or the data flow server in case of MavenProperties).

Please re-open this if you think there is anything specific that needs to be considered here.
