### ISSUE TITLE
Fix TCK abstract class

### ISSUE THREAD

**Issue by ericbottard** [spring-cloud/spring-cloud-deployer#144]
Following the upgrade to use the new boot IT annotations, there has been a misunderstanding about how the implicit `Configuration` is being picked up [here](https://github.com/spring-cloud/spring-cloud-deployer/blob/98ffdb78bafd3e60f81608c0c22f1f9ed2fccc3a/spring-cloud-deployer-spi-test/src/main/java/org/springframework/cloud/deployer/spi/test/AbstractIntegrationTests.java#L128-L135)

The maven properties are not created by default, which had to be worked around e.g. in CF using [here](https://github.com/spring-cloud/spring-cloud-deployer-cloudfoundry/commit/7869bd26da0f690088ac86d8debf5f16cdb5cb94)

**Comment by jvalkeal** [comment]
There is a bit cleaner way to import that config class and define repo. This was done for local deployer tests. https://github.com/spring-cloud/spring-cloud-deployer-local/blob/master/spring-cloud-deployer-local/src/test/java/org/springframework/cloud/deployer/spi/local/LocalAppDeployerIntegrationTests.java#L35

**Comment by ericbottard** [comment]
Ah, I was wondering how the local deployer tests could still pass (the docker ones, I understood).

Yes, this is a way of doing it, and I'm afraid it's the "best" (but this shifts the burden of knowing about the superclass config to the specific implementations).

I wonder if we referenced the upperclass Config in the upperclass annotation, and the child only dealt with its own implementation, would that work ? (this is roughly how the previous annotation seemed to work).

**Comment by jvalkeal** [comment]
While being on a `spring-cloud-deployer` those didn't fail because you had that app jar on a local maven repo(due to mvn install or pulled by some other deps). CI build does `mvn install` so it'd get that into reactor build and local repo automatically. Actually I had empty local maven repo on my laptop while being in Finland and `spring-cloud-deployer` build failed if I just did `mvn clean package`.

**Comment by jvalkeal** [comment]
AFAIK, there's no automatic way for tests to import `@Configuration` classes from abstract parent classes as we can't never control how those unit tests are actually configured.

**Comment by ericbottard** [comment]
Some javadoc somewhere (can't remember exactly which class) states that the default is to use any static inner `@Configuration` class(es). But I guess this only applies to the actual concrete class of the test (not inherited, even if annotated, superclasses).
