### ISSUE TITLE
Add support for 'g' as a common suffix for memory

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-deployer#155]

**Comment by gregturn** [comment]
You sure we don't want to make that GB?

**Comment by markfisher** [comment]
+1 I think "mb" and "gb" (case-insensitive) would be better

**Comment by ericbottard** [comment]
Agreed, although maybe not exactly what https://en.wikipedia.org/wiki/Gigabyte says (ie 1000 instead of 1024).
The thing is, though, that -Xmx and friends use `m` and `g`, so people may be used to it as well..

**Comment by gregturn** [comment]
Perhaps, but I was thinking of consistency with Spring Boot's http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto-multipart-file-upload-configuration

**Comment by trisberg** [comment]
Since there doesn't seem to be a commonly used way of defining this - Kubernetes uses MiB/GiB BTW - maybe we should just drop any suffix and have the parameter specify memory in megabytes, without a suffix. Then  implementations can convert the amount to whatever unit used by their platform as they see fit.

**Comment by ericbottard** [comment]
I'd vote for supporting the official (as seen in wikipedia) suffixes. My intent was for deployer-core to expose functionality for implementors to get the amount in the unit that best fits their needs (ie kubernetes could ask for "get the amount in megabytes" and always append MiB).
I'll work on a PR

**Comment by trisberg** [comment]
Wouldn't "MiB" be the wrong suffix for megabytes?

**Comment by ericbottard** [comment]
Got tricked by the wrong common-day usage. I should have written "get the amount in *mebi*bytes" and happen MiB.
You get the idea :)

**Comment by trisberg** [comment]
I do, maybe we should just use getAmountInBytes and let the platform impls figure out how to use it. K8s uses bytes internally BTW.
