### ISSUE TITLE
Manage aether dependencies to be consistent with Spring Boot

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-deployer#169]
Spring Boot CLI (and Spring Cloud Contract) uses aether as well, but with slightly different versions. If we could harmonize, that would be great. In particular the `maven-aether-provider` in this project looks a bit mouldy, and it even depends on a version of aether that is older than the one in this project (which caauses issues for projects that depend on both). I recommend updating to the same versions as used in Spring Boot.

**Comment by markfisher** [comment]
Does it make sense to consider moving the `spring-cloud-deployer-resource-maven` project down to a "commons" layer altogether? (and removing `deployer` from its name). Perhaps there's code duplication between this and the CLI project as well as the version discrepancies?

**Comment by dsyer** [comment]
There's no code duplication, only dependency duplication. But if you want to merge this repo with spring-cloud-commons (is that what you mean), I guess that would give us a good place to control the dependency management.

**Comment by dsyer** [comment]
I see what you mean about the code duplication now. The `spring-cloud-deployer-resource-maven` duplicates some of the concerns of the Boot CLI and the thin launcher (which re-uses code in the CLI). Spring Cloud Contract duplicates it again. We should factor it out I guess.

**Comment by markpollack** [comment]
I'll look to sync up, I had spent some time looking into this since I thought we were depending on the provider that is in the aether project itself vs. the maven provided one.  hopefully it is just a point release diff that we can handle in a 1.1.1 release.

**Comment by markpollack** [comment]
Updated from 3.1.0 to 3.2.1 of 

```
				<groupId>org.apache.maven</groupId>
				<artifactId>maven-aether-provider</artifactId>
```

**Comment by markpollack** [comment]
@dsyer I didn't do the full investigation but ran across https://github.com/spring-cloud/spring-cloud-contract/issues/72

Is boot going to update to 3.3.9?

**Comment by dsyer** [comment]
Don't know. I guess maybe we should open an issue in spring-boot.
