### ISSUE TITLE
The TCK shouldn't use app that has service dependencies

### ISSUE THREAD

**Issue by trisberg** [spring-cloud/spring-cloud-deployer#17]
The TCK now uses the `integration-test-processor` which has dependencies on a Redis service being available in order to run. Since this is now independent of Spring Cloud Data Flow and Spring Cloud Stream maybe we should just use a simple Boot app without any service dependencies.

**Comment by markfisher** [comment]
+1

**Comment by ericbottard** [comment]
> The TCK now uses the integration-test-processor which has dependencies on a Redis service being available in order to run

Does it? This is not intentional. Is it because it inherits the parent pom? I'm all for making it the most simple app indeed

**Comment by pperalta** [comment]
I just tried a build without Redis and it fails.
