### ISSUE TITLE
UriRegistryPopulator should not ignore exception for invalid app names

### ISSUE THREAD

**Issue by trisberg** [spring-cloud/spring-cloud-deployer#176]
The UriRegistryPopulator should not ignore IllegalArgumentException [1] when populating the registry from a properties file. This can lead to invalid data getting registered causing problems for users of the app registry.

[1] https://github.com/spring-cloud/spring-cloud-deployer/blob/2c2a0d18cf7271d349a2517aed53ea4f7834edb2/spring-cloud-deployer-resource-support/src/main/java/org/springframework/cloud/deployer/resource/registry/UriRegistryPopulator.java#L85

**Comment by trisberg** [comment]
I also don't think we should accept an empty or invalid URI [2] since that can cause issues for users of the app registry. Data Flow currently throws a fit if this is the case.

[2] https://github.com/spring-cloud/spring-cloud-deployer/blob/2c2a0d18cf7271d349a2517aed53ea4f7834edb2/spring-cloud-deployer-resource-support/src/main/java/org/springframework/cloud/deployer/resource/registry/UriRegistryPopulator.java#L91-L94

**Comment by trisberg** [comment]
There is some confusion between the different implementations for the `UriRegistry` implementations. While the JavaDocs specifies to return "IllegalArgumentException if no URI is registered with the key", only the in memory implementation follows this. It's also possible to get an IllegalArgumentException if the app key is not valid for the RdbmsUriRegistry in DataFlow which requires a <type>.<name> style for app names. We should clarify the JavaDocs and use `null` as a return value to indicate app not found and log or rethrow IllegalArgumentException for invalid app names.

**Comment by ilayaperumalg** [comment]
> We should clarify the JavaDocs and use null as a return value to indicate app not found and log or rethrow IllegalArgumentException for invalid app names.

I think we should always throw IllegalArgumentException when the app is not found. Also, not sure what do you mean by `invalid` app names. Is it just the app name with invalid characters?

**Comment by ilayaperumalg** [comment]
> The UriRegistryPopulator should not ignore IllegalArgumentException [1] when populating the registry from a properties file.

I believe the `IllegalArgumentException` at the UriRegistryPopulator needs to be ignored when the app is not found (throws IllegalArgumentException) and need to register the app by ignoring the exception thrown.

**Comment by trisberg** [comment]
The invalid app name is something that's part of Data Flow - it requires a `type.name` style app name for the registration, like `source.time`. If there is no dot then it's an illegal app name and the find method should throw an IllegalArgumentException, but this is already taken by using that exception to signal app-not-found.
