### ISSUE TITLE
Add environment/platform info API

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-deployer#183]
As a user, I'd like to call an API to gather platform info, so I could use it to probe and aggregate all runtime details. 

This API, depending on the platform where it's invoked from, it could potentially give us these details: https://github.com/spring-cloud/spring-cloud-dataflow/wiki/Reporting-Issues

**Comment by jvalkeal** [comment]
http://hortonworks.com/blog/introducing-hortonworks-smartsense/ is the way HW helps customers to know/fix issues. It even can upload diagnostics back to HW.

**Comment by gregturn** [comment]
@sabbyanandan Can't we plug in one of those github templates for issues to request requires details?

**Comment by sabbyanandan** [comment]
Hi, @gregturn. With this API, we hope to probe and gather all the platform specifics on-demand as opposed to _requesting_ for the details. This would be handy from support standpoint; especially, given that we have multiple platforms with different versions that we are supporting.

**Comment by trisberg** [comment]
Should this be under Data Flow?

**Comment by ghillert** [comment]
@trisberg Would be a separate issue I would think. I looked at it somewhat and discussed it a bit with @sabbyanandan. We would need to identify some commonalities between implementations that we can return. E.g. 

CF has:
https://apidocs.cloudfoundry.org/252/info/get_info.html

Yarn has:
https://hadoop.apache.org/docs/r2.7.2/hadoop-yarn/hadoop-yarn-site/ResourceManagerRest.html#Cluster_Information_API

We would then need an issue for the Data Flow Server - to:

* implement the REST APIs
* possibly include version in from the Server Implementation itself (e.g. CF Data Flow Server version + Git Hash)

* Next, would be an issue for the Shell
* Finally, an issue for the Dashboard UI to include this information on the about page

We may also consider this as part of this effort: https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/91

**Comment by ghillert** [comment]
Issue is also related to https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/160
