### ISSUE TITLE
Support iterating all the remote repositories when resolving the artifacts in case of failure

### ISSUE THREAD

**Issue by ilayaperumalg** [spring-cloud/spring-cloud-deployer#192]
As a user, I'd like to try all the provided remote repositories when one of the repository URLs returned error.

**Comment by ericbottard** [comment]
I would hope this is provided by aether, if not by default!

**Comment by ilayaperumalg** [comment]
I could verify that `DefaultArtifactResolver` (from aether) handles it by iterating over all the available remote repositories when performing the download of artifacts.
