### ISSUE TITLE
Add option for command line args

### ISSUE THREAD

**Issue by mminella** [spring-cloud/spring-cloud-deployer#20]
As a developer, I want to be able to configure command line args as a separate set of properties to be passed to an app when it's deployed.

Backstory
When running something like a task or Spring Batch job, there are properties I'll want to configure once per app definition (database connection information for example), and yet there are items that I will want to be different with each launch (for example processing date).  I'd expect the current properties value in an AppDefinition to address the first set of values (database properties), but not the second (especially within the SCDF environment).  This story is to create a subclass of AppLaunchRequest that has an additional set of properties for tasks that will be passed to the boot jar as command line args.

**Comment by markpollack** [comment]
This could also apply to long running apps, so why not push it up one level?

**Comment by mminella** [comment]
No real objections there although I'm not sure they are as necessary for streams as they are for tasks.

**Comment by markpollack** [comment]
Would just simply the model...

**Comment by jvalkeal** [comment]
@markfisher @markpollack  Before I try this would you be awfully against if in `AppDeploymentRequest` we'd add:
```
Set<String> commandlineArgs;
```
I know that we can pass in properties via `environmentProperties` but those are not meant for app itself, thought `LocalTaskLauncher` is adding everything from there into environment which is wrong. Anyway passing anything into app via `properties` is just a bootifull way to add configuration options. As some programs are more inclined to read process command line args we probably need to add that to `AppDeploymentRequest`. And it'd be a raw set(not key/value) passed in by a user.

Then it'd be up to a deployer to compile those into runtime in a best way it can. Like with `java -jar myawesome.jar >1 /stdout >2 /stderr` you may need to find a correct location where to place `-Dxxx`, `-X`, `-XX` and other generic args.

**Comment by markfisher** [comment]
In the local impl, we have `javaCmd` in the `LocalDeployerProperties` (which has a prefix of `deployer.local`). Is that potentially related?

**Comment by jvalkeal** [comment]
Well partially, as it really is just a `javaCmd` and might be used for `-Dxxx`, `-X`, `-XX` but not for actual args.
```
ProcessBuilder builder = new ProcessBuilder(properties.getJavaCmd(), "-jar", jarPath);
```
