### ISSUE TITLE
LocalDeployerProperties fails on executing java on windows

### ISSUE THREAD

**Issue by pjannapu** [spring-cloud/spring-cloud-deployer#225]
As part of an effort to setup and run Spring Cloud Dataflow (SCDF) local server as per the instructions provided at (http://cloud.spring.io/spring-cloud-dataflow/ precisely at step 2), I was running into an exception when starting the SCDF local server on my **Windows 10** workstation. The server startup fails with an error that says .

"Error creating bean with name 'spring.cloud.deployer.local-org.springframework.cloud.deployer.spi.local.LocalDeployerProperties': Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.cloud.deployer.spi.local.LocalDeployerProperties]: Constructor threw exception; nested exception is **java.lang.IllegalArgumentException: Java executable discovered via 'java.home' system property 'C:\Installed_software\java\jre-8u131' is not executable or does not exist.** "

On further debugging the problem, it turned out that the method deduceJavaCommand(), in the class, org.springframework.cloud.deployer.spi.local.LocalDeployerProperties, has an assertion on
"javaExecutable.canExecute()" which fails on windows. This is because on Windows, the Java executable is named as "java.exe" but not "java". 

A hack for this problem would be to create an empty file named "java" (no extensions) and run the jar. It would be great if someone can put in a fix for the issue. As the problem was discovered as part of local setup instructions, I felt that it would be great if someone from Pivotal can again verify the local setup instructions that are provided as part of such tutorials on Spring cloud. Thanks for your time!

-PJ.

**Comment by sabbyanandan** [comment]
This issue was moved to spring-cloud/spring-cloud-deployer-local#60

**Comment by sabbyanandan** [comment]
This is being addressed via: spring-cloud/spring-cloud-deployer-local#59.
