### ISSUE TITLE
MavenArtifactResolver disregards the  non-proxy-hosts configuration

### ISSUE THREAD

**Issue by jvmlet** [spring-cloud/spring-cloud-deployer#242]
Please honor the  `--maven.proxy.non-proxy-hosts` parameter  when building remote repositories.

**Comment by ilayaperumalg** [comment]
Hi @jvmlet , 

The property `maven.proxy.non-proxy-hosts` is already exposed in MavenProperties. Did you mean to say, it is not working as expected?

**Comment by jvmlet** [comment]
Hi
Yes, setting this property has no effect and I don't see any logic  in [MavenArtifactResolver](https://github.com/spring-cloud/spring-cloud-deployer/blob/master/spring-cloud-deployer-resource-maven/src/main/java/org/springframework/cloud/deployer/resource/maven/MavenArtifactResolver.java) that honors `non-proxy-hosts`  field from `MavenProperties` object

**Comment by jvmlet** [comment]
Sorry, there is `proxySelector.add(proxy, this.properties.getProxy().getNonProxyHosts());` logic, let me check once again the behaviour...

**Comment by ilayaperumalg** [comment]
@jvmlet Did you get a chance to check this out? Please let us know if you still see the issue.

**Comment by ilayaperumalg** [comment]
Closing this for now and please feel to re-open if you still see any issue.

**Comment by jvmlet** [comment]
Hi @ilayaperumalg , I've checked it . I'm still experience the  `Bad Gateway (502)` problem due to `non-proxy-hosts`  issue.
 I'm running  the local SCDF server with below `java` arguments :

````
-Dhttp.proxyHost=xxxx
-Dhttp.proxyPort=9480
-Dhttp.nonProxyHosts=hotToEscape
-jar spring-cloud-dataflow-server-local-1.3.0.M3.jar
--maven.remote-repositories.repo1.url=http://hotToEscape:8443/artifactory/ASP-Snapshot-Local
--maven.remote-repositories.repo1.auth.username=xxx
--maven.remote-repositories.repo1.auth.password=xxx
--maven.remote-repositories.repo1.snapshot-policy.update-policy=always
--maven.remote-repositories.repo1.snapshot-policy.checksum-policy=warn
--maven.proxy.host=xxx
--maven.proxy.port=9480
--maven.proxy.non-proxy-hosts=hotToEscape
````

**Comment by jmchen** [comment]
This issue is not resolved. Please reopen.
The proxySelector is setup inside DefaultRepositorySystemSession. 
However, org.eclipse.aether.transport.http.HttpTransporter is not getting proxy from repositorySession, instead it gets proxy from Repository directly.

`    

    HttpTransporter( RemoteRepository repository, RepositorySystemSession session )
        throws NoTransporterException {

        //... omitted for brevity ...
        proxy = toHost( repository.getProxy() );
        repoAuthContext = AuthenticationContext.forRepository( session, repository );
        proxyAuthContext = AuthenticationContext.forProxy( session, repository );

        state = new LocalState( session, repository, new SslConfig( session, repoAuthContext ) );

        //... omitted for brevity
    }
`

According to document of RepositorySystemSession, the ProxySelector within RepositorySystemSession is not meant for Remote Repository, the repository should have its own Proxy selected.

`

     public interface RepositorySystemSession {
        //... omitted for brevity ...
        /**
         * Gets the proxy selector to use for repositories discovered in artifact descriptors. Note that this selector is
         * not used for remote repositories which are passed as request parameters to the repository system, those
         * repositories are supposed to have their proxy (if any) already set.
         * 
         * @return The proxy selector to use, never {@code null}.
         * @see org.eclipse.aether.repository.RemoteRepository#getProxy()
         * @see RepositorySystem#newResolutionRepositories(RepositorySystemSession, java.util.List)
         */
        ProxySelector getProxySelector();
        //... omitted for brevity ...
    }

`
A pull request is created. https://github.com/spring-cloud/spring-cloud-deployer/pull/341
