### ISSUE TITLE
Version 1.3.1.RELEASE

### ISSUE THREAD

**Issue by shahbour** [spring-cloud/spring-cloud-deployer#248]
I was trying to build forked version of `spring-cloud-deployer-kubernetes` but found that
`spring-cloud-deployer-parent` [v1.3.1.RELEASE](http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22spring-cloud-deployer-parent%22) is not found on maven central repo

**Comment by sabbyanandan** [comment]
Hi, @shahbour. Thanks for reporting. We will investigate.

**Comment by jvalkeal** [comment]
I've started a new sync to central. Hopefully that does a trick.

**Comment by jvalkeal** [comment]
Ok, finally these landed to https://oss.sonatype.org/content/repositories/releases/org/springframework/cloud/spring-cloud-deployer-parent/1.3.1.RELEASE. Prob takes while to sync indexes and http://repo1.maven.org.
