### ISSUE TITLE
README request: define "SPI"

### ISSUE THREAD

**Issue by bitops** [spring-cloud/spring-cloud-deployer#249]
As a newcomer to this repo, the term `SPI` is used heavily but not defined anywhere. It would be helpful to have the definition spelled out at least once at the top of the document before using a three-letter abbreviation everywhere. Thanks so much!

**Comment by sabbyanandan** [comment]
Hi, @bitops. SPI stands for "Service Provider Interface". Thanks for the feedback! We will update it. 😄

**Comment by sabbyanandan** [comment]
Addressed in https://github.com/spring-cloud/spring-cloud-deployer/commit/98dc6d38827e9e1bcca2a19fae10a422c277f266.
