### ISSUE TITLE
Add URIRegistry

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-deployer#27]
As a developer, I'd like to implement `URIRegistry` for registering and loading URIs pointing to resources, so I can use it to load Spring Boot applications.

**Acceptance:**
- I can successfully lookup time-source (URI) by passing the name as `time` and the type as `source`
- Unit tests included to simulate this operation
- Docs included

**Comment by pperalta** [comment]
https://github.com/spring-cloud/spring-cloud-deployer/pull/30
