### ISSUE TITLE
Investigate how to retrieve the recent logs of the deployed applications

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-deployer#305]
@sabbyanandan commented on [Wed May 29 2019](https://github.com/spring-cloud/spring-cloud-dataflow/issues/3253)

Explore the options to retrieve the recent logs of the deployed applications for the following platforms.

~- [ ] Local (manual / docker compose)~
- [ ] CF
- [ ] K8s

**Comment by ilayaperumalg** [comment]
Closing this spike as resolved and will have subsequent stories created in the respective projects.
