### ISSUE TITLE
Experiment adding support to cleanup Maven cache directory

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-deployer#325]
As a user, when using the Maven artifact resolution in Cloud Foundry, we run into disk-quota issues as soon as >20 apps with ~50MB size are deployed through SCDF or Skipper. This problem is so quick to run into, and the only way to recover from the situation is to restart the SCDF/Skipper servers.

**Acceptance:**
- Experiment to find an approach to clean-slate the cache directory along with any associated metadata 
- See if the cleanup can be exposed as an API or utility
- Verify it is functional in Local and CF

**Comment by dturanski** [comment]
Closing this since it was resolved by https://github.com/spring-cloud/spring-cloud-deployer-cloudfoundry/pull/323
