### ISSUE TITLE
Allow configuring "preemptive authentication" for remote maven artifactory

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-deployer#331]
As a user, I'm trying to configure "preemptive authentication" against the remote maven artifactory to resolve artifacts with this setting turned-on; however, I'm unable to set that as an option in [`MavenProperties`](https://github.com/spring-cloud/spring-cloud-deployer/blob/master/spring-cloud-deployer-resource-maven/src/main/java/org/springframework/cloud/deployer/resource/maven/MavenProperties.java). 

The underlying Maven Resolver library via [`AuthenticationContext`](https://github.com/apache/maven-resolver/blob/master/maven-resolver-api/src/main/java/org/eclipse/aether/repository/AuthenticationContext.java) doesn't appear to support that as an option. Perhaps due to the security concerns described in the official [Maven guide](https://maven.apache.org/guides/mini/guide-http-settings.html#The_Basics).

**Acceptance:**
- Verify whether this is a required setting for `GET` requests (to resolve and download artifacts — maven guide indicates it will help avoid double transfer of creds in HTTP headers _only_ for `PUT` requests
- If it applies to `GET`, study the possibility of adding support to override and to set `usepreemptive` property as "true" (default = "false")
- If the support is not natively available in Maven Resolver, look for alternative add-on or implement support for it in the SPI
- If we end up adding support for it, let's make sure the javadocs and the ref. guide material is updated
- List any limitations and/or security concerns in the docs
- Include test coverage

**Comment by jvalkeal** [comment]
I didn't even find where in maven sources these are configured. This preemptive auth is not actually part of maven configs as it configures http client what maven uses.

**Comment by jvalkeal** [comment]
Everything mentioned in [HttpClient HTTP Wagon](https://maven.apache.org/guides/mini/guide-http-settings.html) is only available if actual maven build uses build extensions to enable [Maven Wagon](https://maven.apache.org/wagon/). This enabled crazy need for xml configuration in a real maven build.

Did a little experimenting and it needs quite a bit of work in `MavenArtifactResolver` to move to `Wagon` or selectively switch to it. `Pre-emptive` and other stuff is only available via maven wagon providers.

Using wagon would open up other nice opportunities to resolve maven coordinates via other transports like ftp/ssh/git etc.
