### ISSUE TITLE
Prepare for 2.2.1

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-deployer#338]
SPI: 
![image](https://user-images.githubusercontent.com/1562654/75793183-d65ed880-5d23-11ea-9215-7303275d058d.png)

CF:
![image](https://user-images.githubusercontent.com/1562654/75793631-7e74a180-5d24-11ea-917f-fba74cce8c94.png)

**Comment by ilayaperumalg** [comment]
All the associated changes are cherry-picked and merged into Spring Cloud Deployer, SCD Local, SCD K8s, and SCD Cloud Foundry.

Closing this as complete
