### ISSUE TITLE
Fix code scanning alert - Spring Expression DoS Vulnerability

### ISSUE THREAD

**Issue by corneil** [spring-cloud/spring-cloud-deployer#388]
Waiting for Spring Boot 2.7.11

Tracking issue for:
- [ ] https://github.com/spring-cloud/spring-cloud-deployer/security/code-scanning/25
- [ ] https://github.com/spring-cloud/spring-cloud-deployer/security/code-scanning/20
- [ ] https://github.com/spring-cloud/spring-cloud-deployer/security/code-scanning/16
- [ ] https://github.com/spring-cloud/spring-cloud-deployer/security/code-scanning/14
- [ ] https://github.com/spring-cloud/spring-cloud-deployer/security/code-scanning/13
- [ ] https://github.com/spring-cloud/spring-cloud-deployer/security/code-scanning/9
- [ ] https://github.com/spring-cloud/spring-cloud-deployer/security/code-scanning/4
- [ ] https://github.com/spring-cloud/spring-cloud-deployer/security/code-scanning/17
- [ ] https://github.com/spring-cloud/spring-cloud-deployer/security/code-scanning/1

**Comment by onobc** [comment]
Fixed in various commits.
