### ISSUE TITLE
Duplicate Kubernetes pod ids when tasks are launched at the same time

### ISSUE THREAD

**Issue by sayapeg** [spring-cloud/spring-cloud-deployer#399]
When the Spring Cloud DataFlow Server in the Kubernetes environment tries to launch pods for many tasks(200+), we have encountered scenarios where duplicate Pod id is generated for 3-4 pods. I have looked at the [code generating the id](https://github.com/spring-cloud/spring-cloud-deployer/blob/00f9473b790b117ba0fce87dfcc501bf1de0ac0e/spring-cloud-deployer-kubernetes/src/main/java/org/springframework/cloud/deployer/spi/kubernetes/KubernetesTaskLauncher.java#L228), and it encodes the timestamp in milliseconds using the hashid library.

Multiple tasks end up launched simultaneously and with the same pod id. Can we introduce randomness here or another way to ensure pod id uniqueness is not dependent on only the timestamp?

**Comment by einmartwa** [comment]
Observed the same behavior. Currently, we work around by catching the exception and trying to re-launch the desired task once, but a fix in Deployer would be nicer.

**Comment by corneil** [comment]
@onobc I suggest we create a random number within a syncronized block or Lock instead of using millisecond timer.

**Comment by onobc** [comment]
> @onobc I suggest we create a random number within a syncronized block or Lock instead of using millisecond timer.
> 

We can do a concat of the millis + counter suffix.
