### ISSUE TITLE
Update Kubernetes Support Matrix for 2.9.x

### ISSUE THREAD

**Issue by cppwfs** [spring-cloud/spring-cloud-deployer#444]
Update K8's support matrix in Deployer documentation.
Verify microsite and SCDF reference doc matrix's are correct.

**Comment by cppwfs** [comment]
@corneil Have the documentation been updated?

**Comment by onobc** [comment]
The only other location I found the matrix was in the Microsite ([here](https://dataflow.spring.io/docs/installation/kubernetes/compatibility/)).

Update Microsite here https://github.com/spring-io/dataflow.spring.io/commit/130884cbebb950c0d4ef3e28dace2a291af1184a

**Comment by onobc** [comment]
Closed via https://github.com/spring-io/dataflow.spring.io/commit/130884cbebb950c0d4ef3e28dace2a291af1184a
