### ISSUE TITLE
Do not use starter-parents as boms

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-deployer#46]
See https://github.com/spring-cloud/spring-cloud-deployer/blob/master/pom.xml#L41

**Comment by trisberg** [comment]
This was fixed in commit https://github.com/spring-cloud/spring-cloud-deployer/commit/670daa65b2987fec0ede8f4e4d02b5cb97a22c5c#diff-600376dffeb79835ede4a0b285078036
