### ISSUE TITLE
Add URI support for MavenResource

### ISSUE THREAD

**Issue by jvalkeal** [spring-cloud/spring-cloud-deployer#6]
Effectively to play nice with spring `ResourceLoader` we need to able to use format `maven:http://repo.spring.io/libs-snapshot-local/org.springframework.cloud.task.module:timestamp-task:jar:exec:1.0.0.BUILD-SNAPSHOT`.

**Comment by ericbottard** [comment]
IMO, the actual URL from which the resource is ultimately downloaded should not be part of the Reource. It should be part of the ResourceLoader. This is a URLResource, plain and simple.

Shouldn't a MavenResource be something like `maven:<groupId>:<artifactId>:<version>.<etc...>`

**Comment by jvalkeal** [comment]
While you are partly true about that, this allows to define repository url within a resource. Say that user is happy to use default apps/tasks from public repos, but want to run their custom internal app from a local maven repo, we need to have a repo url part of a resource URI then. `ResourceLoader` don't need to use that as URI without host/path is also supported.

**Comment by markfisher** [comment]
I think I agree with @ericbottard that the repository location(s) does not belong in the URI itself (for one thing Maven resolution can take into account multiple repositories as well as the distinction between remote and local).

That said, given how this `MavenResource` currently encapsulates the entire resolution process, we do need a way to provide the repository properties to that instance, unless there is some alternative that still provides the same level of abstraction we're getting here.... where any `Resource` could be provided to the deployer.

**Comment by jvalkeal** [comment]
Well we need to do a custom `ResourceLoader` which would then build actual `Resource`s. Think global settings for multiple maven repos can be done there. Everything around resource loader is kinda tricky because `ApplicationContext` itself is a `ResourceLoader` so IMHO, we get into trouble if we try to use app context. We have had a lot of trouble with these in spring hadoop with its `HdfsResource`.

You really can't change the `ResourceLoader` functionality in `ApplicationContext` without breaking whole functionality. We need to do some prototyping so that `maven`, `http`, `s3`, `hdfs` all work together.

Different servers may want to register different resource types, at least yarn deployer wants to use `HdfsResource` with `hdfs:` `URI`s. So we need to build something keeping this in mind.

Then on a jvm level when working with `URL`s, things gets even more trickier because you need to have schemes registered but you can do that only once per jvm.

URL.class:
```
    public static void setURLStreamHandlerFactory(URLStreamHandlerFactory fac) {
        synchronized (streamHandlerLock) {
            if (factory != null) {
                throw new Error("factory already defined");
            }
            SecurityManager security = System.getSecurityManager();
            if (security != null) {
                security.checkSetFactory();
            }
            handlers.clear();
            factory = fac;
        }
    }
```
