### ISSUE TITLE
Local deployer: How to pass VM arguments?

### ISSUE THREAD

**Issue by YoannBuch** [spring-cloud/spring-cloud-deployer#61]
I'd like to give VM arguments to the local deployer but I don't think it's possible as it is now.

I feel like it should be done in `AbstractLocalDeployerSupport.buildExecutionCommand` right after we set the Java command. 

I see 2 options:

- Make VM arguments a separate member of `AppDeploymentRequest`. But since `AppDeploymentRequest` is generic, maybe introduce a `LocalAppDeploymentRequest`
- Use special environment properties like what was done with `main` and `classpath`

And btw, how was it handled for remote deployers?

**Comment by markfisher** [comment]
Can you provide an example of what you need to provide via system properties?

**Comment by YoannBuch** [comment]
I'd like to set VM options like -Xmx, -javaagent, etc. 

It looks like #107 will do the job :) 

Although I would not name it `systemProperties` but rather `vmOptions`.  What do you think @spencergibb?

**Comment by spencergibb** [comment]
In discussions with @markfisher I'm going to change it to `JAVA_OPTS`.

**Comment by YoannBuch** [comment]
Even better :)

**Comment by spencergibb** [comment]
Closed via afe19b08b0da399b735de75c6e4f051fc768d795. @markfisher any idea on the 1.0.3 release?

**Comment by markfisher** [comment]
@spencergibb we should be able to kick off the 1.0.3 anytime you need it. I don't believe any other dependent projects are awaiting an update yet. CC @sabbyanandan

**Comment by spencergibb** [comment]
@markfisher that would be great if we could get it soon.
