### ISSUE TITLE
Add DeployerIntegrationTestTaskApplication

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-deployer#65]
As a developer, I'd like to add `DeployerIntegrationTestTaskApplication`, so I can use it for IT tests to evaluate `TaskLauncher` implementation across various deployers.

**Comment by markfisher** [comment]
why not rely upon the existing `DeployerIntegrationTestApplication` with its `killDelay` property set? (we could also add an exit code property so that it could exit "normally" after the kill delay if so configured) cc @ericbottard

**Comment by trisberg** [comment]
That sounds like a plan.
