### ISSUE TITLE
Add cleanup(String id) and destroy(String appName) to TaskLauncher interface

### ISSUE THREAD

**Issue by trisberg** [spring-cloud/spring-cloud-deployer#67]
It would be nice to have a `public void cleanup(String id)` and `public void destroy(String appName)` method in the `TaskLauncher` SPI interface since many/most runtimes would need to clean up whatever is created to launch a task.

**Comment by mminella** [comment]
What does "clean up" mean?  I'd assume `delete(String id)` would clean up what the task instance created?  If so, that isn't needed on CF or YARN.  For CF, we'd need a `delete(String taskName)`.  I think more discussion is needed for this before we add it to the top level API...

**Comment by trisberg** [comment]
Changing the suggested new method to be `cleanup(String... id)` method that takes a var arg of execution ids to clean up after. Any implementation that meeds to could also clean up any artifacts created during the launch related to a task although the API is only concerned with task executions. Data Flow could call this when tasks are destroyed but that would require storing the execution ids in the task repository.
