### ISSUE TITLE
Standardize keys for memory, cpu, and disk properties

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-deployer#69]
Memory and Disk size are common properties to set when deploying apps.  They are currently handled by individual deployer implementations defining their own keys.  Making these properties as part of AppDeployer interface will make future additions to Data Flow that enable individual application memory/disk deployment properties be aligned with the code that implements application instance count.  That is, to support 

```
dataflow:> stream deploy --name ticktock --properties "app.time.memory=2048"
```

much like we support 

```
dataflow:> stream deploy --name ticktock --properties "app.time.count=3"
```

See https://github.com/spring-cloud/spring-cloud-dataflow/issues/658

**Comment by trisberg** [comment]
The plan is to add two deployer property constants in the SPI's `AppDeployer` class.

1. `spring.cloud.deployer.memory` for specifying "container" memory in megabytes - `1024` or `1024m` are both acceptable formats

2. `spring.cloud.deployer.cpu` for specifying number of cpu cores, ignored for platforms where this has no effect. Can be specified as a whole number or a decimal fraction. Some platforms (YARN) only supports whole numbers
