### ISSUE TITLE
Remote repository should point to release repo

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-deployer#74]
As a developer, I'd like to change the [remote repository location](https://github.com/spring-cloud/spring-cloud-deployer/blob/300f27063e78d267c2b58c6a6fbdd01a29d9e71f/spring-cloud-deployer-resource-maven/src/main/java/org/springframework/cloud/deployer/resource/maven/MavenProperties.java#L44) to point to `libs-release` instead of `libs-snapshot`.

**Acceptance:**
`remoteRepositories` points to `http://repo.spring.io/libs-release`

**Comment by markfisher** [comment]
we don't want to restrict deployment to released versions, and `libs-snapshot` is a superset

**Comment by sabbyanandan** [comment]
@jvalkeal brought it up the other day. Let's see if he has any additional thoughts to share.

**Comment by markfisher** [comment]
I've got the changes ready for PRs for both deployer (https://github.com/markfisher/spring-cloud-deployer/commit/5cb3c931931d30a8d3ab3383a3d452da749a6d0b) and dataflow (https://github.com/markfisher/spring-cloud-dataflow/commit/9cd41ffc096c3fe8470026c45df25fedf47607fa), BUT before actually submitting those PRs, we need to decide what we want the default to be for the actual Data Flow Servers. As you can see in the latter commit referenced above, I specified the "libs-snapshot" repository in the `dataflow-server.yml` file for the Local Data Flow Server's starter. Alternatively, users may specify that property in any of the usual ways (cmd-line arg, system property, env var, or even an `application.yml` in the working directory). In any case we need to document how to configure it, but my primary concern with pushing this through as the default *now* is that we do not yet have any "out-of-the-box" apps in the `libs-release` repository. Should we wait to submit these PRs until we have an initial GA release of those apps?

**Comment by markpollack** [comment]
Maybe we should not provide any default, much like we don't provide any apps registered OOTB, why should we force upon them a default repo location.  Thinking it through, we may even want to expose an endpoint that updates that maven repo location or expand the app register command to take the actual repo location into account.

**Comment by ilayaperumalg** [comment]
Please note that currently the remote repository is set [here] (https://github.com/spring-cloud/spring-cloud-deployer/blob/master/spring-cloud-deployer-resource-maven/src/main/java/org/springframework/cloud/deployer/resource/maven/MavenArtifactResolver.java#L73)

**Comment by markpollack** [comment]
On second thought, if we don't provide a default, it probably makes the OOTB getting started experience for the local server to be quite a PITA.

**Comment by markfisher** [comment]
we decided to go with an empty map for the `remoteRepositories` within `MavenProperties` - at this level we shouldn't be concerned with any getting started experience

**Comment by markfisher** [comment]
resolved (as described in the previous comment) via https://github.com/spring-cloud/spring-cloud-deployer/pull/81
