### ISSUE TITLE
spring-cloud-deployer-resource-maven should support remote repository authentication

### ISSUE THREAD

**Issue by donovanmuller** [spring-cloud/spring-cloud-deployer#75]
Following on from [this Gitter conversation](https://gitter.im/spring-cloud/spring-cloud?at=57691e73bd67400679dba6ce), it should be possible to provide authentication details for remote Maven repositories the same way authentication is [supported for HTTP proxies](https://github.com/spring-cloud/spring-cloud-deployer/blob/master/spring-cloud-deployer-resource-maven/src/main/java/org/springframework/cloud/deployer/resource/maven/MavenArtifactResolver.java#L98).

**Comment by ilayaperumalg** [comment]
Hi @donovanmuller, 

The remote repository authentication is supported. You can refer the below properties and set them in spring-boot way. Here is the sample properties that are set as environment properties:

```
export MAVEN_LOCAL_REPOSITORY=mylocalMavenRepo
export MAVEN_REMOTE_REPOSITORIES=repo1,repo2
export MAVEN_OFFLINE=true
export MAVEN_PROXY_PROTOCOL=https
export MAVEN_PROXY_HOST=host1
export MAVEN_PROXY_PORT=8090
export MAVEN_PROXY_NON_PROXY_HOSTS='host2|host3'
export MAVEN_PROXY_AUTH_USERNAME=user1
export MAVEN_PROXY_AUTH_PASSWORD=passwd
```

More documentation is [here] (https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/spring-cloud-dataflow-docs/src/main/asciidoc/getting-started.adoc)

**Comment by donovanmuller** [comment]
@ilayaperumalg Those properties are to configure the credentials for the [HTTP proxy support](https://github.com/spring-cloud/spring-cloud-deployer/blob/master/spring-cloud-deployer-resource-maven/src/main/java/org/springframework/cloud/deployer/resource/maven/MavenArtifactResolver.java#L98), not the actual Maven remote repository(s) authentication.
