### ISSUE TITLE
Maven artifact resolver should allow a "pom" artifact type to be resolved

### ISSUE THREAD

**Issue by donovanmuller** [spring-cloud/spring-cloud-deployer#79]
Based on the question [raised on Gitter](https://gitter.im/spring-cloud/spring-cloud?at=576baa6f80f1c6a5257e5a97), would it be possible to include the ability to resolve the "pom" artifact extension/type in addition the the "jar" extension/type?

Currently, only the ["jar" extension](https://github.com/spring-cloud/spring-cloud-deployer/blob/master/spring-cloud-deployer-resource-maven/src/main/java/org/springframework/cloud/deployer/resource/maven/MavenArtifactResolver.java#L307) is resolved. However, I have a use case where I require the "pom" extension to be resolved (and cached locally) to be [processed/parsed](https://maven.apache.org/ref/3.3.9/maven-core/apidocs/org/apache/maven/project/ProjectBuildingResult.html) later in a custom deployer. 
I.e. some values are extracted from the `pom.xml` of the app being deployed (in addition to the `AppDefinition`) which enable certain features of the custom deployer.

I could resolve the `pom` outside `spring-cloud-deployer-resource-maven` but since Maven's default behaviour is to resolve and cache the jar as well as the pom artifact, hopefully this is something that could be supported by `spring-cloud-deployer-resource-maven`?

**Comment by donovanmuller** [comment]
This is in context of [this post](http://blog.switchbit.io/spring-cloud-deployer-openshift) around a deployer implementation for OpenShift. See [here](http://blog.switchbit.io/spring-cloud-deployer-openshift/#gettingstarted).

**Comment by sabbyanandan** [comment]
PR's were merged; closing the related issue. Thanks for the contributions, @donovanmuller! 😄

**Comment by ilayaperumalg** [comment]
yes, thank you for the contributions @donovanmuller
