### ISSUE TITLE
maven.remote-repositories.test1.auth.xxx does not bind correctly

### ISSUE THREAD

**Issue by donovanmuller** [spring-cloud/spring-cloud-deployer#85]
Following on from #75, the suggested way of specifying the auth credentials for a remote repository:

```
java -jar spring-cloud-dataflow-server-local-1.0.0.BUILD-SNAPSHOT.jar  \
--maven.localRepository=mylocal 
--maven.remote-repositories.test1.url=remoteURL1 \
--maven.remote-repositories.test1.auth.username=user1 \
--maven.remote-repositories.test1.auth.password=pass1 --maven.proxy.host=proxy1 \
--maven.proxy.port=9010 --maven.proxy.auth.username=proxyuser1 \
--maven.proxy.auth.password=proxypass1
```

does not bind for the `auth` property. I.e. always null.

The following does bind correctly:

```
java -jar spring-cloud-dataflow-server-local-1.0.0.BUILD-SNAPSHOT.jar  \
--maven.localRepository=mylocal \
--maven.remoteRepositories.test1.url=remoteURL1 \
--maven.remoteRepositories.test1.auth.username=user1 \
--maven.remoteRepositories.test1.auth.password=pass1 --maven.proxy.host=proxy1 \
--maven.proxy.port=9010 --maven.proxy.auth.username=proxyuser1 \
--maven.proxy.auth.password=proxypass1
```

I.e. `--maven.remote-repositories.test1.auth.xxx.` does not bind but `--maven.remoteRepositories.test1.auth.xxx.` does.

**Comment by ilayaperumalg** [comment]
Hi @donovanmuller,

I have just verified this and could see the `MavenProperties` updated correctly.  Attaching the properties that my IDE shows when I run the `local` dataflow server with these options:

```
java -jar spring-cloud-dataflow-server-local-1.0.0.BUILD-SNAPSHOT.jar \
--maven.localRepository=mylocal --maven.remote-repositories.test1.url=remoteURL1 \
--maven.remote-repositories.test1.auth.username=user1 \
--maven.remote-repositories.test1.auth.password=pass1
```
![screen shot 2016-07-01 at 6 34 03 pm](https://cloud.githubusercontent.com/assets/151690/16522331/d6e2899e-3fba-11e6-85b5-32ac2c6d8819.png)

**Comment by donovanmuller** [comment]
Hmm, just re-ran and it's working now 😄 .
Apologies for the run around...
