### ISSUE TITLE
Enhance TCK wrt count, instanceIndex, and deploymentProperties

### ISSUE THREAD

**Issue by ericbottard** [spring-cloud/spring-cloud-deployer#95]
Now that the role of `deploymentProperties` has been clarified, the abstract test class that is used for the TCK could
* validate that `count` is properly handled (esp. given that the in-process option is no longer available)
* validate that `deploymentProperties` are not passed to the deployed app

**Comment by trisberg** [comment]
What about "GROUP_PROPERTY_KEY", don't  think we have any tests verifying that it is used, although, the intended expectations of its use isn't really specified by the SPI.

**Comment by trisberg** [comment]
Should we make a 1.0.x branch and switch to 1.1.0.BUILD-SNAPSHOT or does this belong in 1.0.3.BUILD-SNAPSHOT?

**Comment by sabbyanandan** [comment]
This is not big enough to switch to 1.1.x, yet. @markfisher: thoughts?

**Comment by trisberg** [comment]
it's labeled as 1.1.0.M1

**Comment by markfisher** [comment]
I think we went back and forth a few times. At one point, the issue was labeled 1.1.0.M1. The question is whether that was our final decision. I don't recall. CC @markpollack

**Comment by ericbottard** [comment]
Given that it adds tests only, and that local deployer passes as is, i'd
say maintenance is fine. (ie no bug fixed, let alone no new feature).

Le 22 juil. 2016 10:51 PM, "Thomas Risberg" <notifications@github.com> a
écrit :

**Comment by markfisher** [comment]
I'm okay with that, and it is the simpler option ;)

**Comment by markpollack** [comment]
+1
