### ISSUE TITLE
Explore options to handle the remote resource caching for runtimes with limited disk space (e.g. Cloud Foundry).

### ISSUE THREAD

**Issue by tzolov** [spring-cloud/spring-cloud-deployer#98]
The [DelegatingResourceLoader](https://github.com/spring-cloud/spring-cloud-deployer/blob/master/spring-cloud-deployer-resource-support/src/main/java/org/springframework/cloud/deployer/resource/support/DelegatingResourceLoader.java#L122)  implementation caches remote resources in a local cache directory. 
Runtimes such as Cloud Foundry have limited disk space (usually ~ 2GB). So the dataflow server can exceed the cachedir space with few dataflow streams.

**Comment by sabbyanandan** [comment]
The original scope of the issue is still relevant. We are to explore LRU caching mechanism and extension applicability within the Aether library.

**Comment by ericbottard** [comment]
Addressed via https://github.com/spring-cloud/spring-cloud-dataflow-server-cloudfoundry/pull/237
